import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { lora } from "@/lib/fonts";

const metadata: Metadata = {
  title: "Quiz Bot Gemini",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={lora.className}>
        <main>
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
