import type { Metadata } from "next";
import { Lora, Metamorphous } from "next/font/google";
import "./globals.css";


const inter = Lora({ 
  variable: '--font-inter',
  subsets: ["latin"],
});

export const metamorphouse = Metamorphous({
  subsets: ['latin'],
  variable: '--font-metamorphous',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: "Quiz Bot Gemini",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
